export const staticText = {
  gameTitle: 'Connect4',
  newGame: 'New Game',
  saveGame: 'Save Game',
  restartGame: 'Restart Game',
  undoMove: 'Undo Last Move',
  boardSize: 'Board size',
  draw: 'Draw Game!',
  gameOver: 'Game over! Start a new game.',
  currentPlayer: 'Player',
  player1: 'Player 1 wins!',
  player2: 'Player 2 wins!',
  smallBoard: 'Small (3 in row)',
  mediumBoard: 'Medium (4 in row)',
  largeBoard: 'Large (5 in row)',
};
